apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-db-migration.fullname" . }}
  labels:
    {{- include "app-db-migration.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-db-migration.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-db-migration.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "nginx"
          image: "{{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}"
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
        - name: "php-fpm"
          image: "{{ .Values.image.fpm.repository }}:{{ .Values.image.fpm.tag }}"
          imagePullPolicy: {{ .Values.image.fpm.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.fpmPort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.fpmPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.fpmPort }}
