name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "FPM: Publish to Registry"
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: zhutik/example-helm-db-migration-php-fpm
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: _docker/php/Dockerfile
          context: .

      - name: "Nginx: Publish to Registry"
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: zhutik/example-helm-db-migration-nginx
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: _docker/nginx/Dockerfile
          context: .
